name: Preview - Build & Submit (TestFlight + Play Internal)

on:
  push:
    branches: ["preview"]

jobs:
  ios_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm i -g eas-cli

      - name: Build iOS (preview)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build -p ios --profile preview --non-interactive

      - name: Submit iOS (TestFlight)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas submit -p ios --profile preview --latest --non-interactive

  android_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm i -g eas-cli

      - name: Build Android (preview)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build -p android --profile preview --non-interactive

      - name: Submit Android (Play Internal)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas submit -p android --profile preview --latest --non-interactive
