name: Preview - Build and submit to TestFlight + Google Play (Internal)

on:
  push:
    branches: ["preview"]

jobs:
  # build_android_preview:
  #   name: Build Android (preview - store)
  #   type: build
  #   params:
  #     platform: android
  #     profile: preview

  # submit_android_preview:
  #   name: Submit Android (internal track)
  #   type: submit
  #   needs: [build_android_preview]
  #   params:
  #     platform: android
  #     profile: preview

  build_ios_preview:
    name: Build iOS (preview - store)
    type: build
    params:
      platform: ios
      profile: preview

  submit_ios_preview:
    name: Submit iOS (TestFlight)
    type: submit
    needs: [build_ios_preview]
    params:
      platform: ios
      profile: preview
