name: Preview - Build and submit to TestFlight + Google Play (Internal)

on:
  push:
    branches: ["preview"]

jobs:
  # =========================
  # iOS – TestFlight
  # =========================
  build_ios_preview:
    name: Build iOS (preview - TestFlight)
    type: build
    params:
      platform: ios
      profile: preview

  submit_ios_preview:
    name: Submit iOS (TestFlight)
    type: submit
    needs: [build_ios_preview]
    params:
      platform: ios
      profile: preview
      build_id: ${{ needs.build_ios_preview.outputs.id }}

  # =========================
  # Android – Play Internal
  # =========================
  build_android_preview:
    name: Build Android (preview - Internal)
    type: build
    params:
      platform: android
      profile: preview

  submit_android_preview:
    name: Submit Android (Play Internal)
    type: submit
    needs: [build_android_preview]
    params:
      platform: android
      profile: preview
      build_id: ${{ needs.build_android_preview.outputs.id }}
