name: Master - Build & Submit (Production)

on:
  push:
    branches: ["master"]

jobs:
  ios_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm i -g eas-cli

      - name: Build iOS (production)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build -p ios --profile production --non-interactive

      - name: Submit iOS (App Store Connect)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas submit -p ios --profile production --latest --non-interactive

  android_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm i -g eas-cli

      - name: Build Android (production)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build -p android --profile production --non-interactive

      - name: Submit Android (Play Production)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas submit -p android --profile production --latest --non-interactive
