name: Master - Deploy to production

on:
  push:
    branches: ["master"]

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint
    environment: production

  get_android_build:
    name: Check for existing Android build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      profile: production

  get_ios_build:
    name: Check for existing iOS build
    needs: [fingerprint]
    type: get-build
    params:
      fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
      profile: production

  build_android:
    name: Build Android (production)
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: production

  build_ios:
    name: Build iOS (production)
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: production

  submit_android_build:
    name: Submit Android build
    needs: [build_android]
    if: ${{ needs.build_android.outputs.build_id }}
    type: submit
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}

  submit_ios_build:
    name: Submit iOS build
    needs: [build_ios]
    if: ${{ needs.build_ios.outputs.build_id }}
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}

  publish_android_update:
    name: Publish Android OTA update
    needs: [get_android_build]
    if: ${{ needs.get_android_build.outputs.build_id }}
    type: update
    params:
      branch: production
      platform: android

  publish_ios_update:
    name: Publish iOS OTA update
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    type: update
    params:
      branch: production
      platform: ios
