name: Master - Build and submit (Production)

on:
  push:
    branches: ["master"]

jobs:
  # -----------------------
  # iOS (App Store Connect)
  # -----------------------
  build_ios_production:
    name: Build iOS (production)
    type: build
    params:
      platform: ios
      profile: production

  submit_ios_production:
    name: Submit iOS (App Store Connect)
    type: submit
    needs: [build_ios_production]
    params:
      platform: ios
      profile: production

  # -----------------------
  # Android (Google Play)
  # -----------------------
  build_android_production:
    name: Build Android (production)
    type: build
    params:
      platform: android
      profile: production

  submit_android_production:
    name: Submit Android (production track)
    type: submit
    needs: [build_android_production]
    params:
      platform: android
      profile: production
