name: Master - Build and submit (Production)

on:
  push:
    branches: ["master"]

jobs:
  build_android_production:
    name: Build Android (production)
    type: build
    params:
      platform: android
      profile: production

  submit_android_production:
    name: Submit Android (production track)
    type: submit
    needs: [build_android_production]
